---
apiVersion: v2
appVersion: v0.5.0
version: 0.1.0
name: kwatch
description: |4
    Helm chart to deploy Kwatch on Your kubernetes cluster.
type: application
keywords:
- kwatch
maintainers:
- name: yaser
  email: yaserkalali.work@gmail.com
  url: github.com/yaskinny
home: https://github.com/abahmed/kwatch
...
