apiVersion: v2
name: kwatch
version: "0.10.3"
appVersion: "v0.10.3"
description: monitor all changes in your Kubernetes(K8s) cluster, detects crashes
  in your running apps in realtime, and publishes notifications to your channels (Slack,
  Discord, etc.) instantly
type: application
home: https://kwatch.dev
icon: https://kwatch.dev/img/kwatch-logo.png
sources:
  - https://github.com/abahmed/kwatch
keywords:
  - kwatch
  - kubernetes
  - monitoring
  - crash-reporting
  - event-notifier
maintainers:
  - email: a.ahmed1026@gmail.com
    name: Abdelrahman Ahmed
    url: github.com/abahmed
  - email: yaserkalali.work@gmail.com
    name: yaser
    url: github.com/yaskinny

