---
commonLabels: {}
commonAnnotations: {}

privateRegistries: []


kwatch:
  strategy:
    type: Recreate
    # type: RollingUpdate
    # maxSurge: 1
    # maxUnavailable: 0
  image: ghcr.io/abahmed/kwatch:{{ .Chart.AppVersion }}
  imagePullPolicy: Always
  resources:
    # requests:
    #   memory: 128Mi
    #   cpu: 100m
    limits:
      memory: 128Mi
      cpu: 100m
  securityContext:
    runAsUser: 65534
    runAsGroup: 65534
    runAsNonRoot: true
    privileged: false
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
      - ALL
  envFrom: []
  config:
    ## if You want to provide your own config as a secret or configMap
    ## set create to false and set appropriate values
    # configMap:
    #   name: my-config
    #   key: kwatch
    ## OR for secret
    # secret:
    #   name: my-secret-config
    #   key: secret-kwatch
    create: true
    configTemplate:
      namespaces: []
      maxRecentLogLines: 0
      ignoreFailedGracefulShutdown: false
      disableUpdateCheck: false
      alert:
        slack:
          webhook: ""
          title: ""
          text: ""
        pagerduty:
          integrationKey: ""
        discord:
          webhook: ""
          title: ""
          text: ""
        telegram:
          token: ""
          chatId: ""
        teams:
          webhook: ""
          title: ""
          text: ""
        rocketchat:
          webhook: ""
          text: ""
        mattermost:
          webhook: ""
          title: ""
          text: ""
        opsgenie:
          apiKey: ""
          title: ""
          text: ""
...
