maxRecentLogLines: 0
alert:
  slack:
    webhook: ""
  pagerduty:
    integrationKey: ""
  discord:
    webhook: ""
  telegram:
    token: ""
    chatId: ""
  teams:
    webhook: ""
namespaces:
  - default