maxRecentLogLines: 100
alert:
  slack:
    webhook: ""
  pagerduty:
    integrationKey: ""
  discord:
    webhook: ""
  telegram:
    token: ""
    chatId: ""
  email:
    form: ""
    password: ""
    host: ""
    port: ""
    to: ""
  teams:
    webhook: ""
  rocketchat:
    webhook: ""
  mattermost:
    webhook: ""
  opsgenie:
    apiKey: ""
namespaces:
  - default
  - kwatch
